### ISSUE TITLE
[support] clarification on simplest possible setup (re: pupa)

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#118]
Hey James, quick support question: I've been trying to get this running on both Ubuntu 14.04 and Debian Jessie, but no dice. Quick question for sanity checking: Should it be possible to run some of this with stock pupa? As in, if I just `pip3 install pupa`, what am I losing?

PS, do you have a more synchronous mode of communication with the outside world? :) If not, mind if I register #opennorth for you on freenode, and if you felt like it, you could direct any IRC users in the group over there? (I personally leave stuff like this in my auto-join channel list, so I could always be there if anyone drops in.) I can probably also add botbot.me logging so that any conversations there can be deeplinked from any relevant github issues, so that those IRC convos aren't so transient ([for example](https://botbot.me/freenode/codeforcanada/2015-05-25/?msg=40104190&page=1)).

**Comment by jpmckinney** [comment]
What error(s) are you seeing when following the [install instructions](https://github.com/opencivicdata/scrapers-ca#usage)?

**Comment by patcon** [comment]
I've blown it away in the time since, but a django one about "Models not found" was the main killer. I'll post the exact error soon when I run into it again, and link to the vagrant VM that produced it. (slow connection building the vm where I'm located.)

To be fair, I believe I was getting it in a jessie VM  with both pupa's official release and your own built from the repo.

I did follow the instructions, but I think it's missing a few things. At the very least, it seems I needed the packages `libxml2-dev` and `libxslt-dev` for building the py pkg `lxml`, and I think `libgeos-dev` for running django correcting with GEOS support. Anyhow, I'll have that VM pushed soon, and I'll update docs if it turns out anything is needed

**Comment by jpmckinney** [comment]
Sounds good, please PR any missing steps on Ubuntu/Debian.

**Comment by patcon** [comment]
:+1:

**Comment by patcon** [comment]
Still working on `pip install pupa` (and not the whole requirements.txt, as that's not pinned and wouldn't strike me as the best place to troubleshoot). Seems to use pupa, the system needs an `opencivicdata` database and a `pupa` superuser. Sound right?

https://gist.github.com/patcon/c9c1bd33bba941b0666d

Also, when I *do* use the requirements.txt right after (where stock pupa seemed to generally work), I get the same error about models that I mentioned before:

https://gist.github.com/patcon/5ee82ae793a8c6d7ccb1

Not sure if you've rebuilt lately. I thought maybe it's the unpinned pupa that might be causing the second error (using the requirements.txt). If so, I was thinking maybe the first error of `unrecognized arguments: ca` (with stock pupa) might have been because `python-opencivicdata-divisions` was missing during the first run. But even when I go back to stock pupa (now, with the divisions package installed), I still get that same error: `django.core.management.base.CommandError: Error: unrecognized arguments: ca`

Any thought or feedback is appreciated.

**Comment by patcon** [comment]
OK, so even though `dbinit` was failing, it seems I can still use the `update` command to run scrapers. Go figure.

Also, needed to edit db_settings.py, as the db cnnx string wasn't specifying a user, and so was assuming a user named `pupa` existed to match the `pupa` database

**Comment by jpmckinney** [comment]
Not sure what's happening there. I have neither an `opencivicdata` database, nor a `pupa` user. This is running on Heroku without issue, so not sure what the problem is.

**Comment by patcon** [comment]
Hm. I'll blow it away once more and build from scratch :/

**Comment by Menerve** [comment]
I tried to do the same thing and got the same error on Ubuntu 14.04.
The installation isn't working as smoothly as on OS X due to the postgresql setup not working in the same way. I don't know what's happening either.

I managed to run ```python manage.py syncdb --noinput``` successfully but ```dbinit``` is failing.

**Comment by patcon** [comment]
Oh man, thanks for piping up @Menerve. I was starting to think I was either incompetent or crazy, as no one else had hit any problems :)

OK, that gives me the confidence to keep working through this later

**Comment by Menerve** [comment]
So, some news on this.

The error ```Models aren't loaded yet``` is because ```django.setup()``` fails silently in https://github.com/opencivicdata/pupa/blob/master/pupa/cli/__main__.py#L34:

```python
try:
    django.setup()
except django.db.utils.OperationalError:
    pass
```

What django is saying is that it can't connect to the database (```fe_sendauth: no password supplied```) because to connect to a Postgresql database you need to provide a user and a password (https://docs.djangoproject.com/en/1.7/intro/tutorial01/#database-setup) which don't appear in https://github.com/opencivicdata/pupa/blob/master/pupa/settings.py nor in https://github.com/opennorth/scrapers_ca_app/blob/master/scrapers_ca_app/settings.py
That's why both commands ```python manage.py syncdb``` and ```pupa dbinit ca``` fail with the same error.

Adding those lines to both pupa settings and scraper_ca_app settings seem to fix the problem:
```
DATABASES['default']['USER'] = 'username'
DATABASES['default']['PASSWORD'] = 'password'
```

Now, I'm not sure why it's working on OSX and Heroku. Any thoughts on this @jpmckinney ?

**Comment by jpmckinney** [comment]
Heroku sets a `DATABASE_URL` environment variable that sets a user and password. On OS X, with Homebrew, the default user is the `USER` environment variable, and the default password is empty, for which a Postgres user exists.

The issue was https://github.com/opencivicdata/pupa/issues/87 I opened a PR to not silently fail. #91
