### ISSUE TITLE
Toronto: add videos as eventagendamedialink entries

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#127]

**Comment by jpmckinney** [comment]
Do you intend to close these? I don't use GitHub issues as a parking lot for ideas.

**Comment by patcon** [comment]
Yep, these are for me to work on. Just stubs of things I was finding as I was working with the data

**Comment by patcon** [comment]
If the open issues mess with your github workflow, I guess I could fork and keep my own issue queue, so just lemme know

**Comment by jpmckinney** [comment]
Cool, just checking. I look forward to reviewing your changes!

**Comment by patcon** [comment]
If nothing arrives, then I suck, in which case don't hesitate to give me shit about it and make mean comments about my mother :)
