### ISSUE TITLE
[question] objection to adding internal ids for government systems?

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#137]
Any objection to saving internal IDs from the Toronto City Council system in the pupa db, perhaps in the `extras` column (which all objects seem to have)? For example, meetings get a `meetingId` in their system, and so do committees (`decisionBodyId`). In generating direct links to source data, it's seems useful to have these in the pupa database.

Any objection?

Alternatively, we could theoretically store this in the [alternative name/identifier field](https://opencivicdata.readthedocs.org/en/latest/data/organization.html#alternate-names-identifiers) but it seems that only persons and orgs have this, so it would be a bit inconsistent.

Thoughts?

**Comment by jpmckinney** [comment]
Person and Organization (committees) inherit the IdentifierMixin so they'll have an `add_identifier` method.

Meetings (events) don't, so I guess add to `extras` in that case.

**Comment by jpmckinney** [comment]
Or make a PR to Pupa to add that mixin, since Popolo's Event schema does have that.
