### ISSUE TITLE
[question] why was the event scraper pulled?

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#138]
I'm just about to jump into this, as it's the main thing I need for the project I'm working on. To be efficient with my time, can I ask for the context on disabling the event scraper?

**Comment by jpmckinney** [comment]
The event scraper was very slow - and although at the time I had identified some basic things to change to make it faster, I didn't have the time to refactor. You can enable/rework it.

**Comment by patcon** [comment]
Thanks for the info!

**Comment by patcon** [comment]
Think it'd be alright to just scrape X days into the future and the past, and then following trails accordingly, using this view:

http://app.toronto.ca/tmmis/meetingCalendarView.do?function=calendarCellView&date=3&month=11&year=2015

So it would assume that a big scrape had been imported manually, and then it would scan around the current day, looking for cancellations or updated agendas or vote results. Once I get your previous scraper working (it's progressing great btw), I'm planning to deal with updates that way.
