### ISSUE TITLE
Toronto: Scrape historical elected officials

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#142]
The current elected official page has much more detail, but would be great to have a longer term option to scrape.

http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=834689fe9c18b210VgnVCM1000003dd60f89RCRD

**Comment by patcon** [comment]
It seems silly to only have PDFs of this data, so I sent an email to the open data contact address. I offered to write a script for them that would parse the PDFs and generate CSVs, if they were willing to host the converted CSVs on the portal

**Comment by jpmckinney** [comment]
:+1:

**Comment by patcon** [comment]
Got a reply, and was given permission to post (

> Hi Patrick!
>
> We wouldn't be able to install and/or use the scraper at our end on our pages for all kinds of reasons. But, that being said, we have a tools and help page that we want to be crowd sourced. If you were to put your tool on the web and made it available, we would reference it on our help page. This is exactly the kinds of things we want the community to let us know so we can share.
>
> Let me know what you might be thinking around your own release and web etc.
>
> Keith McDonald

When I asked to be able to quote him in this issue, he was understandably wary of his response being posted publicly without context, and added:

> Sure ... but I want to be clear there are legal reason we can't accept an offer of a scraper that the developer community should know and acknowledge ... I also hope you agree we're suggesting a valid other option yes? Further, we agree the pdf is not good but haven't been able to move the divisions off of that format for this data.
>
> Let me know what you think ...
>
> Keith

Anyhow, I'll work on something and keep him in the loop.
