### ISSUE TITLE
[meta] active scraper that doesn't run by default

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#143]
I was hoping to move toward having long-running historical scrapers (like `disabled/ca_on_toronto/events.py`) that aren't run on `pupa update ca_on_toronto` but which can be run manually with `pupa update ca_on_toronto events`.

Thoughts? And if you think it makes sense, would this be something sensible to add here, or in pupa?

**Comment by jpmckinney** [comment]
Add it here. Only the "people" scrapers run on a cron schedule on Heroku currently. I can configure additional scrapers, and those scrapers can accept command-line options to not do historical scrapes.

**Comment by patcon** [comment]
:+1: Thanks!

**Comment by jpmckinney** [comment]
I think this is resolved.
