### ISSUE TITLE
Store some objective measure of "vote split" in vote_event extras field

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#144]
Thinking that it would be nice to sort by "controversy" for certain cases. Might this be something we could store in the OCD object itself, or should this be pushed into downstream projects.

Related: https://github.com/designcofounders/toronto-city-hall/issues/9

**Comment by jpmckinney** [comment]
I think that's for downstream only. Pupa should just be facts. The VoteEvent can store `counts` though. See http://popoloproject.com/specs/vote-event.html

**Comment by patcon** [comment]
Yeah, I'm using the word "controversy", but imho this is a statistical fact not too unlike storing count. But anyhow, I'll instead investigate postgres features for indexed expressions
