### ISSUE TITLE
How to add other_name on city council org

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#145]
Given how util.py works right now, I'm not sure how to get the council Organization object in another scraper so that I can add organizationname's and organizationlink's

Any thoughts on how best to do this?

**Comment by jpmckinney** [comment]
I haven't looked at the code, but you can inherit and override any behaviour, no?

**Comment by patcon** [comment]
OK, sorted it out. Did I mention that I don't always feel like I'm a coder? :)

This will be done as part of #146

**Comment by jpmckinney** [comment]
Ha, I'm just not-picky about data modelling :)
