### ISSUE TITLE
Toronto: Sort out distinction between motions and bill actions

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#148]
Not quite sure how to think about these yet, and whether our current bill scraper currently stands to be teased a part a bit. (?) Ideally, I'd like to get things into a format that Councilmatic worked really well, but I'm still investigating that.

Any feedback is appreciated on how the bill scraper might expect to evolve.

Reference: http://www.toronto.ca/legdocs/bylaws/law-home/about-bylaws-and-code.htm

**Comment by jpmckinney** [comment]
What's a "bill action"?

**Comment by patcon** [comment]
This is the "action" in I'm unsure how to differentiate from vote event motions -- perhaps they overlap.

https://opencivicdata.readthedocs.org/en/latest/data/bill.html#sponsors-and-actions

It seems relevant as I'm interested in adapting councilmatic to Toronto, and they make heavy use of actions:

- https://github.com/opencivicdata/scrapers-us-municipal/blob/master/nyc/bills.py
- http://nyc.councilmatic.org/legislation/int-798-2015/

**Comment by jpmckinney** [comment]
I had treated Toronto motion as equal to Pupa bill. If Toronto motion becomes Pupa action, then what is the Pupa bill?

**Comment by patcon** [comment]
I'll read through their scraper and ask around before commenting further
