### ISSUE TITLE
[meta] storing geo points on bills?

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#149]
- http://app.toronto.ca/tmmis/viewAgendaItemHistory.do?item=2015.NY10.43
- http://app.toronto.ca/tmmis/getAddressList.do?function=getAgendaItemAddressList&agendaItemId=61134

You mentioned "area" in popolo, so for points, I'm looking at this:
http://www.w3.org/ns/locn#locn:geometry

How's this work for you in extras?

```json
{
  "area": [
    {   
      "geometry": {
        "type": "point",
        "coordinates": [
          43.7744611,
          -79.34206360000002
        ]
      },
      "properties": {
        "address": "106 Parkway Forest Drive, Toronto, Ontario"
      }
    }   
  ]
}
```

EDIT: editted suggestion EDIT: again

**Comment by patcon** [comment]
Or maybe this is better:

```json
{
  "area": [
    {   
      "name": "106 Parkway Forest Drive, Toronto, Ontario",
      "geometry": {
        "type": "point",
        "coordinates": [
          43.7744611,
          -79.34206360000002
        ]
      },
    }   
  ]
}
```

**Comment by patcon** [comment]
Better, per-meeting option for parsing:
http://app.toronto.ca/tmmis/getAddressList.do?function=getMeetingAddressList&meetingId=4825

**Comment by jpmckinney** [comment]
An address is a point, not an area. I would use that vocabulary's `fullAddress` (`full_address`) and `geometry` (GeoJSON) terms.

**Comment by patcon** [comment]
Awesome. Thanks. I'm not totally sure how to interpret specs like this. Would this conform?

```json
extras: {
  "locations": [
    {
      "address": {
        "full_address": "106 Parkway Forest Drive, Toronto, Ontario"
      },
      "geometry": {
        "type": "point",
        "coordinates": [
          43.7744611,
          -79.34206360000002
        ]
      }
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Looks good. Though GeoJSON would capitalize "Point".

**Comment by patcon** [comment]
amended

**Comment by patcon** [comment]
To confirm, are intersections still ok to use in full_address fields, in your opinion? (Toronto uses those often in their system)

**Comment by jpmckinney** [comment]
Seems fine to me, if that's how the source expresses the information.

**Comment by patcon** [comment]
Also, GO TO BED.
