### ISSUE TITLE
Toronto: Run flake8

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/scrapers-ca#152]
A good idea to run `flake8 .` before submitting any PRs.

**Comment by patcon** [comment]
Great idea. I have def been working in the dark on python style :)

I'll submit travis tests when I get around to it

**Comment by patcon** [comment]
This can be closed in favour of the PR

**Comment by jpmckinney** [comment]
Just put "closes #152" in the PR description so both get closed if I merge.
