### ISSUE TITLE
Toronto: Add councillor pseudonyms back into people scraper

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#155]
Spin-off from https://github.com/opencivicdata/scrapers-ca/issues/151

**Comment by jpmckinney** [comment]
Pretty sure I preserved that - though the scraper is failing right now because Toronto has invalid phone numbers (which have been reported).

**Comment by patcon** [comment]
Perhaps I just don't know how to CSVScraper works :) It just looked like it couldn't possibly have enough to work properly

**Comment by patcon** [comment]
The photos for councillor Cho and Davis are dead links. If you still have a line of communication open about updates to the list, would you mind mentioning them?

(In the meantime, I've updated the csv gist, but the link here is a direct to the old commit.)
