### ISSUE TITLE
add_contact method in utils.py is broken

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#189]
I think it broke when we started lower-casing in header_converter:
https://github.com/opencivicdata/scrapers-ca/blob/master/utils.py#L218

And now the contact detail type map returns nothing, at least for toronto, for which the key being looked up is "email":
https://github.com/opencivicdata/scrapers-ca/blob/master/utils.py#L24-L50

Not having experience with other cities, how might you suggest resolving this? Is the CONTACT_DETAIL_X_MAP part still used in other cities?

**Comment by patcon** [comment]
Ugh. Nevermind. Toronto isn't getting contact data put into the tables, but I now realize it's not related to above. I'll keep investigating, but nevermind for now

**Comment by patcon** [comment]
OK, so is it that a membership is the only thing that gets contact details?

**Comment by jpmckinney** [comment]
Generally, contact details relate to a person's membership. If you were to add contact details to a person directly, then semantically that would be to contact them outside the context of their employment, which I don't this is a relevant use case.

**Comment by patcon** [comment]
ok, while this will require more complicated logic in any system building on OCD data, it does strike me as being more sensible :) Drats to the complexity of the real world!
