### ISSUE TITLE
Toronto: Find related agenda items

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#195]
http://docs.opencivicdata.org/en/latest/data/bill.html#other-related-bills

Can probably do this via regex search of full text:

```
([A-Z]{2}\d+\.\d+)
```

Any thoughts on how we'd need to expand the spec to allow more than companion bills. Toronto has a bad habit of creating new agenda items when things come back from certain internal bodies (ie staff), so would be nice to explicitly connect all mentioned agenda items. We can figure out more semantic ways of associating them later.

**Comment by patcon** [comment]
Ah, it appears that we already have more than the docs claim. Awesome.
https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/common.py#L98-L103

**Comment by patcon** [comment]
Actually, I don't think those cover it. For my general purposes (ie before we know what time of relationship), I'd like to simply add a "relates-to". This could perhaps be a two-way relation, as it would be nice if a relation was added back to the one that mentions that other one.

Thoughts?

**Comment by jpmckinney** [comment]
Would the best solution be to use `add_related_bill` and expand the options for `BILL_RELATION_TYPES`?
