### ISSUE TITLE
Toronto: Scrape semantic deferral data

### ISSUE THREAD

**Issue by patcon** [opencivicdata/scrapers-ca#200]
In Toronto, items are often deferred to a specific date/meeting. Would be interesting if this were possible to resolve, provided the meeting schedule is published and also scraped.

For example, on the March 31st committee meeting here (scroll down):
http://app.toronto.ca/tmmis/viewAgendaItemHistory.do?item=2015.HL7.6#

> #### City Council Decision
> 
> City Council on March 31 and April 1, 2016, deferred consideration of Item HL7.6 until the May 3 and 4, 2016 City Council meeting.

/cc @fgregg longshot, but is this anything that has an analog in legistar data?

**Comment by fgregg** [comment]
what do you mean by resolved?

On Thu, May 19, 2016 at 9:35 PM, Patrick Connolly <notifications@github.com>
wrote:

> In Toronto, items are often deferred to a specific date/meeting. Would be
> interesting if this were possible to resolve, provided the meeting schedule
> is published and also scraped.
>
> For example, on the March 31st committee meeting here (scroll down):
> http://app.toronto.ca/tmmis/viewAgendaItemHistory.do?item=2015.HL7.6#
>
> City Council Decision
>
> City Council on March 31 and April 1, 2016, deferred consideration of Item
> HL7.6 until the May 3 and 4, 2016 City Council meeting.
>
> /cc @fgregg <https://github.com/fgregg> longshot, but is this anything
> that has an analog in legistar data?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-ca/issues/200>
>



-- 
773.888.2718

**Comment by patcon** [comment]
@fgregg As in, so the actions in Councilmatic can potentially be formatted like **Deferred to [May 3, 3016](toronto.councilmatic.org/event/city-council-2016-05-03-0900)** and link to the future event, much like actions currently can read as **Referred to [Government Management Committee](toronto.councilmatic.org/committee/government-management-committee)**

**Comment by fgregg** [comment]
Is this what you want:

Attach an reference to an event to a bill action as a related entity, and
have pupa resolve the event reference to an event entity?

That seems very reasonable, assuming that the event entity exists to be
resolve to. Is that the case?

**Comment by patcon** [comment]
Exactly. If it's not already a feature, I know you have it set up to resolve orgs from reference dicts, so I could start looking into how it would work for events where a "name" and "date" are available.

**Comment by fgregg** [comment]
It sounds reasonable to me. Go for it.
