### ISSUE TITLE
ca_ns_cape_breton refuses python-requests user-agent

### ISSUE THREAD

**Issue by cmyr** [opencivicdata/scrapers-ca#211]
Not sure how to proceed on this; the server hosting http://www.cbrm.ns.ca/mayor-council-2.html is explicitly returning 403 when the user-agent is python-requests.

repro:

```sh
curl "http://www.cbrm.ns.ca/mayor-council-2.html"
curl -H "User-Agent: python-requests/2.6.0" "http://www.cbrm.ns.ca/mayor-council-2.html"

```

The first works and the second doesn't. The obvious solution would be a custom user-agent, but I'm not sure if there's any policy here?

**Comment by jpmckinney** [comment]
You can use the same user-agent as in this scraper: https://github.com/opencivicdata/scrapers-ca/blob/4fa36f2b6e07f6a9f0a257fc074b863fbf90c4d8/disabled/ca_qc_mercier/people.py#L10

**Comment by cmyr** [comment]
great @jpmckinney thanks for the quick response.
