### ISSUE TITLE
confused about ca_ab issue

### ISSUE THREAD

**Issue by cmyr** [opencivicdata/scrapers-ca#213]
ca_ab isn't currently working, because there's a new party, the 'United Conservatives'. Adding this to the `PARTIES` lookup table gets the _scraper_ working again, but then the pupa update fails with 

`pupa.exceptions.UnresolvedIdError: cannot resolve pseudo id to Organization: ~{"classification": "party", "name": "United Conservative"}`. 

I feel like I've been confused about something similar to this in the past. @jpmckinney What (loosely) is going on here? we're checking the generated json against some canonical datasource? do we generate this?

(I'm now very confident I've asked a very similar question before. I'll do some digging and see if I can find that)

**edit**: (for posterity there's some useful information in https://github.com/opencivicdata/ocd-division-ids/pull/147, but it doesn't address this particular question)

**edit 2**: there's a similar issue in my recent halifax fix: `pupa.exceptions.UnresolvedIdError: cannot resolve pseudo id to Post: ~{"label": "District 16 Bedford\u2014Wentworth", "role": "Councillor", "organization__classification": "legislature"}`. So I'm clearly doing something wrong.

**Comment by jpmckinney** [comment]
I think you just need to add an entry for the party to https://github.com/opencivicdata/scrapers-ca/blob/master/ca_ab/__init__.py

**Comment by cmyr** [comment]
@jpmckinney ah okay I hadn't noticed that _init__.py was populated. 👍
