### ISSUE TITLE
Last name does not match regex validation in Langley

### ISSUE THREAD

**Issue by rafe-murray** [opencivicdata/scrapers-ca#359]
I have been having an issue where one of the councillors' last names is vanPopta which doesn't match the regex which validates the names. I can think of two options to work around this: 
1. I change the name to a name that matches the regex, i.e., Vanpopta
2. The regex for validation gets changed to allow for this type of name
I discussed with @seamuslee001 and he thought that option 2 was better. @jpmckinney what is your recommended approach?

The page with her name: https://www.tol.ca/en/the-township/misty-vanpopta.aspx
The relevant scraper: https://github.com/opencivicdata/scrapers-ca/blob/eec11c735f3779d444abb5f5563e045c3904bf80/ca_bc_langley/people.py

**Comment by jpmckinney** [comment]
I've updated the regex. try now?

**Comment by rafe-murray** [comment]
Fixed. Thanks!
