### ISSUE TITLE
Ontario representatives outdated at opennorth.ca?

### ISSUE THREAD

**Issue by DrMeers** [opencivicdata/scrapers-ca#449]
e.g. http://scrapers.herokuapp.com/represent/ca_on/ includes current representatives like "Tyler Allsopp", however https://represent.opennorth.ca/representatives/ontario-legislature/?limit=1000 does not -- has something broken in between @jpmckinney ?

**Comment by jpmckinney** [comment]
I don't know, I see Tyler at https://represent.opennorth.ca/representatives/ontario-legislature/?limit=1000

**Comment by jpmckinney** [comment]
Looks like someone broke the cron job. It's running now.

**Comment by DrMeers** [comment]
Thanks @jpmckinney !
